### Get All Products
GET http://0.0.0.0:8080/products
Accept: application/json

### Add a new Product
POST http://0.0.0.0:8080/add-product
Content-Type: application/json

{
  "upc": 2,
  "name": "Smartwatch",
  "description": "Watch that tracks your activity and lifestyle"
}
